name: artifact
on: push
env:
  RUST_TOOLCHAIN: "nightly-2024-04-30"
  CARGO_UNSTABLE_SPARSE_REGISTRY: "true"
  UNSAFE_PYO3_SKIP_VERSION_CHECK: "1"
jobs:

  manylinux_2_17_amd64:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: [
          { version: '3.12' },
          { version: '3.11' },
        ]
    env:
      CC: "clang"
      CFLAGS: "-Os -fstrict-aliasing -fno-plt -flto=full -emit-llvm"
      LDFLAGS: "-fuse-ld=lld -Wl,-plugin-opt=also-emit-llvm -Wl,--as-needed -Wl,-zrelro,-znow"
      RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=lld -C linker-plugin-lto -C lto=fat -C link-arg=-Wl,-zrelro,-znow -Z mir-opt-level=4 -Z virtual-function-elimination -Z threads=4 -D warnings"
      PATH: "/__w/orjson/orjson/.venv/bin:/github/home/.cargo/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    container:
      image: fedora:41
    steps:

    - name: cpuinfo
      run: cat /proc/cpuinfo

    - name: Build environment pre-clone
      run: |
        dnf install -y rustup clang lld python${{ matrix.python.version }} git
        rustup-init --default-toolchain "${RUST_TOOLCHAIN}-x86_64-unknown-linux-gnu" --profile minimal --component rust-src -y

    - uses: actions/checkout@v4

    - name: Build environment post-clone
      run: |
        cargo fetch --target=x86_64-unknown-linux-gnu &

        mkdir .cargo
        cp ci/config.toml .cargo/config.toml

        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv --python python${{ matrix.python.version }}
        uv pip install --upgrade "maturin>=1,<2" -r test/requirements.txt -r integration/requirements.txt

    - name: maturin
      run: |
        maturin build --release --strip \
          --features=avx512,no-panic,unstable-simd,yyjson \
          --compatibility manylinux_2_17 \
          --interpreter python${{ matrix.python.version }} \
          --target=x86_64-unknown-linux-gnu
        uv pip install target/wheels/orjson*.whl

    - run: pytest -s -rxX -v -n 4 test
      env:
        PYTHONMALLOC: "debug"

    - name: Store wheels
      if: "startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v4
      with:
        name: orjson_manylinux_2_17_amd64_${{ matrix.python.version }}
        path: target/wheels
        overwrite: true
        retention-days: 1

